# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'iCocosLive' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for iCocosLive

pod “AFNetworking”
pod “SDWebImage”
pod “FastImageCache”
pod “YYKit”
pod “MJRefresh”
pod “MJExtension”
pod “MBProgressHUD”
pod “AsyncDisplayKit”
pod “JSPatch”
pod “FMDB”
pod “Masonry”
pod ‘pop’
pod 'JKCategories'
#pod 'PYSearch'
pod 'PNChart'

end
